const CREATED = 201;
const BAD_REQUEST = 400;
const UNAUHTORIZED_ACCESS = 401;
const SUCCESS = 200;
const SERVER_ERROR = 500;
const NOT_FOUND = 404;
export { CREATED, BAD_REQUEST, UNAUHTORIZED_ACCESS, SUCCESS, SERVER_ERROR, NOT_FOUND };
