export const LOGIN_USERS_DETAILS_REQUEST = 'LOGIN_USERS_DETAILS_REQUEST';
export const LOGIN_USERS_DETAILS_SUCCESS = 'LOGIN_USERS_DETAILS_SUCCESS';
export const LOGIN_USERS_DETAILS_FAILURE = 'LOGIN_USERS_DETAILS_FAILURE';

export const GET_LEAVE_TYPES_SUCCESS = 'GET_LEAVE_TYPES_SUCCESS';
export const GET_LEAVE_TYPES_FAILURE = 'GET_LEAVE_TYPES_FAILURE';
export const GET_LEAVE_TYPES_REQUEST = 'GET_LEAVE_TYPES_REQUEST';

export const APPLY_FOR_LEAVE_SUCCESS = 'GET_LEAVE_TYPES_SUCCESS';
export const APPLY_FOR_LEAVE_FAILURE = 'GET_LEAVE_TYPES_FAILURE';
export const APPLY_FOR_LEAVE_REQUEST = 'GET_LEAVE_TYPES_REQUEST';

export const GET_ALL_HOLIDAY_SUCCESS = 'GET_ALL_HOLIDAY_SUCCESS';
export const GET_ALL_HOLIDAY_FAILURE = 'GET_ALL_HOLIDAY_FAILURE';
export const GET_ALL_HOLIDAY_REQUEST = 'GET_ALL_HOLIDAY_REQUEST';

export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';

export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAILURE = 'GET_ROLES_FAILURE';
export const GET_ROLES_REQUEST = 'GET_ROLES_REQUEST';
