export const LOGIN_USERS_DETAILS_REQUEST = 'LOGIN_USERS_DETAILS_REQUEST';
export const LOGIN_USERS_DETAILS_SUCCESS = 'LOGIN_USERS_DETAILS_SUCCESS';
export const LOGIN_USERS_DETAILS_FAILURE = 'LOGIN_USERS_DETAILS_FAILURE';

export const GET_LEAVE_TYPES_SUCCESS = 'GET_LEAVE_TYPES_SUCCESS';
export const GET_LEAVE_TYPES_FAILURE = 'GET_LEAVE_TYPES_FAILURE';
export const GET_LEAVE_TYPES_REQUEST = 'GET_LEAVE_TYPES_REQUEST';

export const APPLY_FOR_LEAVE_SUCCESS = 'GET_LEAVE_TYPES_SUCCESS';
export const APPLY_FOR_LEAVE_FAILURE = 'GET_LEAVE_TYPES_FAILURE';
export const APPLY_FOR_LEAVE_REQUEST = 'GET_LEAVE_TYPES_REQUEST';

export const GET_ALL_HOLIDAY_SUCCESS = 'GET_ALL_HOLIDAY_SUCCESS';
export const GET_ALL_HOLIDAY_FAILURE = 'GET_ALL_HOLIDAY_FAILURE';
export const GET_ALL_HOLIDAY_REQUEST = 'GET_ALL_HOLIDAY_REQUEST';

export const GET_APPLIED_LEAVES_REQUEST = 'GET_APPLIED_LEAVES_REQUEST';
export const GET_APPLIED_LEAVES_FAILURE = 'GET_APPLIED_LEAVES_FAILURE';
export const GET_APPLIED_LEAVES_SUCCESS = 'GET_APPLIED_LEAVES_SUCCESS';

export const UPDATE_LEAVE_APPLICATION_REQUEST = 'UPDATE_LEAVE_APPLICATION_REQUEST';
export const UPDATE_LEAVE_APPLICATION_FAILURE = 'UPDATE_LEAVE_APPLICATION_FAILURE';
export const UPDATE_LEAVE_APPLICATION_SUCCESS = 'UPDATE_LEAVE_APPLICATION_SUCCESS';
