export const LOGIN_USERS_DETAILS_REQUEST = 'LOGIN_USERS_DETAILS_REQUEST';
export const LOGIN_USERS_DETAILS_SUCCESS = 'LOGIN_USERS_DETAILS_SUCCESS';
export const LOGIN_USERS_DETAILS_FAILURE = 'LOGIN_USERS_DETAILS_FAILURE';

export const GET_ALL_HOLIDAY_SUCCESS = 'GET_ALL_HOLIDAY_SUCCESS';
export const GET_ALL_HOLIDAY_FAILURE = 'GET_ALL_HOLIDAY_FAILURE';
export const GET_ALL_HOLIDAY_REQUEST = 'GET_ALL_HOLIDAY_REQUEST';
